name: CI

on:
  push:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build docker image
        run: |
          cd ${GITHUB_WORKSPACE} || exit 1
          docker build -t "retail-api:latest" .
