name: 'On PR Created'
on:
  pull_request_target:
    types: [opened, reopened]
    
jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "Env Type: pr createed"
      - uses: actions/checkout@v3
  call-sub-workflow:
    uses: /.github/workflows/process-workflow.yml@main
    with:
      enviroment: dev  
