name: 'On PR Created'
on:
  workflow_dispatch:
    inputs:
      enviroment:
        required: true
        type: choice
        options:
        - dev
        - staging
        - Integration
    
jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "Env Type: pr createed"
      - uses: actions/checkout@v3
  call-sub-workflow:
    uses: aziz781/retail-api/.github/workflows/process-workflow.yml@main
    with:
      enviroment: dev  
