name: 'On PR Created'
on:
  pull_request_target:
    types: [opened,reopened]

  workflow_dispatch:
    inputs:  
      env_type:
        required: true
        type: choice
        options:
        - dev
        - staging
        - Integration
    
jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "Env Type: pr createed"
      - uses: actions/checkout@v3
  call-sub-workflow:
    uses: aziz781/retail-api/.github/workflows/process-workflow.yml@master
    with:
      env_type: dev  
    secrets:   
      gha_token: "${{ secrets.GITHUB_TOKEN }}"  
